In [2]:
import numpy as np

In [20]:
np.arange(0,11,3)

array([0, 3, 6, 9])

One and Two dimentional arrays

In [31]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [32]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Equally spaced array

In [39]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

Identity Matrix

In [23]:
np.eye(4)


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Random sample

In [43]:
np.random.rand(2,3)

array([[0.04696264, 0.70210826, 0.44301116],
       [0.34736066, 0.09421715, 0.82280633]])

Random Integers

In [48]:
np.random.randint(1,100,200)

array([57, 47, 74, 53,  4, 17, 43, 60, 31,  7, 51, 76, 66, 51, 81, 55, 57,
       10, 63, 51, 71, 61, 89, 48, 94, 58,  7, 38, 70,  8, 60, 26, 40, 48,
       86,  6, 78, 95, 59, 48, 92,  8,  3, 94, 64, 60, 91, 21, 95, 63, 36,
       63, 81, 18, 71, 49, 85, 22, 62, 28, 37, 65, 40, 79, 46, 70, 31, 13,
       72, 96, 47, 22, 92, 11, 78, 62, 62, 40, 70, 74, 39, 52, 12, 17, 23,
       33, 25, 58, 42, 62, 29, 46, 49, 36, 33, 79, 24, 76,  2, 29, 49, 53,
       93, 34, 11, 46, 28, 98, 47, 98, 46, 13, 28, 14, 26,  6, 59, 55, 39,
       87, 55, 91, 84, 21, 78, 70, 37,  6,  3, 78, 25,  6, 17, 74, 30, 82,
       61, 40, 78, 30, 29, 39, 46, 73, 30, 41, 74, 28, 43, 14, 84, 78, 94,
       24, 21,  1, 22, 99, 36, 87, 86, 37, 59, 45, 44, 62, 90, 97, 57, 26,
       64, 91, 48, 48, 85, 92, 79, 97, 70, 77, 74, 97, 97, 34, 53,  7, 17,
       37, 25,  9, 53, 46, 26, 40, 40, 18, 74, 38,  4, 16])