In [2]:
import numpy as np

In [20]:
np.arange(0,11,3)

array([0, 3, 6, 9])

One and Two dimentional arrays

In [31]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [32]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Equally spaced array

In [39]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

Identity Matrix

In [23]:
np.eye(4)


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Random sample

In [43]:
np.random.rand(2,3)

array([[0.04696264, 0.70210826, 0.44301116],
       [0.34736066, 0.09421715, 0.82280633]])

Random Integers

In [4]:
np.random.randint(1,100,10)

array([71, 15, 65, 23, 66, 98, 93, 72, 61,  9])

In [6]:
array = np.random.randint(1,100,25)

In [8]:
array

array([59, 52, 95, 60, 23, 25, 23, 72, 62, 42, 40, 65, 90,  7, 64, 88, 60,
       76, 11, 36, 98, 27, 62, 67, 99])

In [10]:
np.reshape(array,(5,5))

array([[59, 52, 95, 60, 23],
       [25, 23, 72, 62, 42],
       [40, 65, 90,  7, 64],
       [88, 60, 76, 11, 36],
       [98, 27, 62, 67, 99]])

In [13]:
np.shape(array)

(25,)

In [15]:
newarray = np.reshape(array,(5,5))

In [16]:
newarray.shape

(5, 5)

Indexing Array

In [19]:
array_2d = np.reshape(array,(5,5))

In [20]:
array_2d

array([[59, 52, 95, 60, 23],
       [25, 23, 72, 62, 42],
       [40, 65, 90,  7, 64],
       [88, 60, 76, 11, 36],
       [98, 27, 62, 67, 99]])

In [23]:
array_2d[:3,:]

array([[59, 52, 95, 60, 23],
       [25, 23, 72, 62, 42],
       [40, 65, 90,  7, 64]])

In [25]:
arr = np.arange(1,11)

In [32]:
arr_gt_5 = arr[arr > 5]

In [33]:
arr_gt_5

array([ 6,  7,  8,  9, 10])